Introduce incremental-build breaking change
- Remove <layout> tags from an included layout
- Also change a view ID in that layout

Results in the old binding not being deleted and noww failing
to compile due to the ID that no longer exists.

/Users/ckroetsc/personal/DataBindingCompileBug/mylibrary/build/generated/ap_generated_sources/debug/out/com/github/cckroets/mylibrary/databinding/IncludedBindingImpl.java:17:
error: cannot find symbol
        sViewsWithIds.put(R.id.old_id, 1);
                              ^
  symbol:   variable old_id
  location: class id